version: "3.9"

services:
  subscription-service:
    build: .
    container_name: subscription-service
    ports:
      - "4003:4003"
    restart: always
    networks:
      - shared-net

networks:
  shared-net:
    external: true
    name: gateway_app-net
