version: "3.9"

services:
  subscription-service:
    container_name: subscription-service
    build: .
    env_file:
      - /home/deploy/config/.env.common
      - .env.staging
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4003/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    ports:
      - "4003:4003"
    restart: always
    networks:
      - gateway_app-net

networks:
  gateway_app-net:
    external: true
