version: "3.9"

services:
  subscription-service:
    container_name: subscription-service
    build: .
    ports:
      - "4003:4003"
    restart: always
    networks:
      - gateway_app-net

networks:
  gateway_app-net:
    external: true
